room_data = {
    "Subtellurian Horrors": {"exits": [("The Crumbling Market (South)", None), ("Dining in Darkness", None)]},
    "Dining in Darkness": {"exits": [("Bandit's Hollow", None), ("Subtellurian Horrors", None)]},
    "Bandit's Hollow": {"exits": [("Delusions of Happiness", "Iron Key"), ("Dining in Darkness", None)]},
    "Delusions of Happiness": {"exits": [("Bandit's Hollow", None)]},
    "Work, Then Die": {"exits": [("Bandit's Hollow", "One-Way"), ("Hope Obstructed", None)]},
    "Senses Lost": {"exits": [("Crossing of Blood", None), ("Desire's Passage", None)]},
    "The Lunatic Veins": {"exits": [("Bandit's Hollow", "One-Way"), ("Tomb of the Reborn", None)]},
    "Tomb of the Reborn": {"exits": [("The Lunatic Veins", None), ("Fool's Gold, Fool's Loss", None)]},
    "Fool's Gold, Fool's Loss": {"exits": [("Tomb of the Reborn", None), ("Kilroy Was Here", None), ("Crossing of Blood", None)]},
    "Kilroy Was Here": {"exits": [("Fool's Gold, Fool's Loss", None), ("A Wager of Noble Gold", None)]},
    "A Wager of Noble Gold": {"exits": [("Kilroy Was Here", None), ("Lambs to the Slaughter", None)]},
    "Lambs to the Slaughter": {"exits": [("A Wager of Noble Gold", None), ("The Ore of Legend", None)]},
    "The Ore of Legend": {"exits": [("Lambs to the Slaughter", None), ("Cry of the Beast", None), ("Suicidal Desires", None)]},
    "Suicidal Desires": {"exits": [("The Ore of Legend", None)]},
    "Cry of the Beast": {"exits": [("The Ore of Legend", None), ("The Fallen Bricklayer", None)]},
    "The Fallen Bricklayer": {"exits": [("Cry of the Beast", None), ("Hall of Contemplation", None), ("Crossing of Blood", None)]},
    "Hall of Contemplation": {"exits": [("The Fallen Bricklayer", None), ("The Abandoned Catspaw", None), ("Hall of the Empty Sconce", None)]},
    "Hall of the Empty Sconce": {"exits": [("Hall of Contemplation", None), ("Acolyte's Burial Vault", None)]},
    "Acolyte's Burial Vault": {"exits": [("Hall of the Empty Sconce", None)]},
    "The Abandoned Catspaw": {"exits": [("Hall of Contemplation", None), ("Crossing of Blood", None)]},
    "Crossing of Blood": {
        "exits": [("The Abandoned Catspaw", None), ("Senses Lost", None), ("The Fallen Bricklayer", None), ("Fool's Gold, Fool's Loss", None)]
    },
    "Desire's Passage": {"exits": [("Senses Lost", None), ("Way of Lost Children", None)]},
    "Way of Lost Children": {"exits": [("Desire's Passage", None), ("Treaty Room", None), ("Hidden Resources", None)]},
    "Hidden Resources": {"exits": [("Way of Lost Children", None)]},
    "Treaty Room": {"exits": [("Way of Lost Children", None), ("The Miner's End", None)]},
    "The Miner's End": {"exits": [("Treaty Room", None), ("Gambler's Passage", None)]},
    "Gambler's Passage": {"exits": [("The Miner's End", None), ("Revelation Shaft", None)]},
    "Revelation Shaft": {"exits": [("Gambler's Passage", None), ("Corridor of Shade", None)]},
    "Corridor of Shade": {"exits": [("Revelation Shaft", None), ("Rue Morgue", None)]},
}
