room_data = {
    "The Cage": {"exits": [("The Soldier's Bedding", None), ("The Cauldron", None)]},
    "The Cauldron": {"exits": [("The Cage", None), ("Wooden Horse", "Tearose Sigil")], "minibosses": ["Gargoyle", "Gargoyle", "Wraith"]},
    "Wooden Horse": {"exits": [("The Cauldron", None), ("Starvation", None)]},
    "Starvation": {"exits": [("Wooden Horse", None), ("The Breast Ripper", None)], "minibosses": ["Wraith", "Mummy"]},
    "The Breast Ripper": {"exits": [("Starvation", None), ("The Wheel", None), ("The Branks", None), ("The Pear", None)]},
    "The Wheel": {"exits": [("The Breast Ripper", None)], "notes": "Chest is warded."},
    "The Branks": {"exits": [("The Breast Ripper", None)], "notes": "Chest is locked."},
    "The Pear": {
        "exits": [("The Breast Ripper", None), ("The Judas Cradle", None), ("The Whirlygig", None)],
        "notes": "Requires difficult jump or Faerie Wing to exit North.",
    },
    "The Judas Cradle": {"exits": [("The Pear", None)]},
    "The Whirlygig": {"exits": [("The Pear", None), ("Spanish Tickler", None)]},
    "Spanish Tickler": {"exits": [("The Whirlygig", None), ("Heretic's Fork", None)], "miniboss": "Wyvern Knight"},
    "Heretic's Fork": {"exits": [("Spanish Tickler", None), ("The Chair of Spikes", None)], "traps": ["Freeze", "Gust"]},
    "The Chair of Spikes": {"exits": [("Heretic's Fork", None), ("Blooding", None)]},
    "Blooding": {"exits": [("The Chair of Spikes", None), ("Bootikens", None)], "traps": ["Death Vapor", "Eruption"]},
    "Bootikens": {"exits": [("Blooding", None), ("Burial", None)]},
    "Burial": {"exits": [("Bootikens", None), ("Burning", None)], "boss": "Iron Golem"},
    "Burning": {"exits": [("Burial", None), ("Cleansing the Soul", None)], "traps": ["Terra Thrust", "Holy Light"]},
    "Cleansing the Soul": {"exits": [("Burning", None), ("The Ducking Stool", None), ("The Garotte", None)]},
    "The Ducking Stool": {"exits": [("Cleansing the Soul", None)]},
    "The Garotte": {"exits": [("Cleansing the Soul", None), ("Hanging", None)]},
    "Hanging": {"exits": [("The Garotte", None), ("Impalement", "Steel Key")]},
    "Impalement": {"exits": [("Hanging", None), ("Knotting", "Platinum Key")]},
    "Knotting": {"exits": [("Impalement", None), ("The Eunics' Lot", None)], "miniboss": "Wyvern Queen"},
}
