room_data = {
    "Dark Abhors Light": {"exits": [("The Sunless Way", "Iron Key"), ("Dream of the Holy Land", None)]},
    "Dream of the Holy Land": {"exits": [("Dark Abhors Light", None), ("The Ore Road", "Aster Sigil")]},
    "The Ore Road": {"exits": [("Dream of the Holy Land", "Aster Sigil"), ("The Air Stirs", None), ("Atone for Eternity", None)]},
    "The Air Stirs": {"exits": [("The Ore Road", None), ("Bonds of Friendship", None), ("Bacchus is Cheap", None)]},
    "Bonds of Friendship": {"exits": [("The Air Stirs", None)]},
    "Atone for Eternity": {"exits": [("The Ore Road", None), ("Stair to Sanctuary", None)]},
    "Stair to Sanctuary": {"exits": [("Atone for Eternity", None), ("The Fallen Hall", None)]},
    "The Fallen Hall": {
        "exits": [("Stair to Sanctuary", None), ("The Rotten Core", None)],
    },
    "The Rotten Core": {"exits": [("The Fallen Hall", None), ("The Dreamer's Climb", None)]},
    "The Dreamer's Climb": {
        "exits": [("The Rotten Core", None), ("The Ore-Bearers", None), ("Sinner's Sustenence", "Eulelia Sigil")],
    },
    "The Ore-Bearers": {"exits": [("The Dreamer's Climb", None), ("Screams of the Wounded", None)]},
    "Screams of the Wounded": {
        "exits": [("The Ore-Bearers", None), ("Bacchus is Cheap", None)],
    },
    "Bacchus is Cheap": {"exits": [("Screams of the Wounded", None), ("The Air Stirs", None)]},
    "Sinner's Sustenence": {"exits": [("The Dreamer's Climb", "Eulelia Sigil"), ("The Timely Dew of Sleep", None)]},
    "The Timely Dew of Sleep": {"exits": [("Sinner's Sustenence", None), ("The Auction Block", None), ("Companions in Arms", "Gold Key")]},
    "Companions in Arms": {"exits": [("The Timely Dew of Sleep", "Gold Key")]},
    "The Auction Block": {"exits": [("The Timely Dew of Sleep", None), ("The Laborer's Bonfire", None), ("Ascension", "Silver Key")]},
    "Ascension": {"exits": [("The Auction Block", "Silver Key"), ("Where the Serpent Hunts", None)]},
    "Where the Serpent Hunts": {"exits": [("Ascension", None), ("Drowned in Fleeting Joy", None), ("Ants Prepare for Winter", None)]},
    "Drowned in Fleeting Joy": {"exits": [("Where the Serpent Hunts", None)]},
    "Ants Prepare for Winter": {"exits": [("Where the Serpent Hunts", None), ("Those who Drink the Dark", "Silver Key")]},
    "The Laborer's Bonfire": {"exits": [("The Auction Block", None), ("Stone and Sulfurous Fire", None), ("Torture Without End", "Melissa Sigil")]},
    "Stone and Sulfurous Fire": {"exits": [("The Laborer's Bonfire", None)]},
    "Torture Without End": {"exits": [("The Laborer's Bonfire", "Melissa Sigil"), ("Way Down",)]},
    "Way Down": {"exits": [("Torture Without End"), ("Excavated Hollow", None), ("Parting Regrets", None)]},
    "Excavated Hollow": {"exits": [("Way Down", None)]},
    "Parting Regrets": {"exits": [("Way Down", None), ("Corridor of Tales", None)]},
    "Corridor of Tales": {"exits": [("Parting Regrets", None), ("Dust Shall Eat the Days", None)]},
    "Dust Shall Eat the Days": {"exits": [("Corridor of Tales", None), ("Hall of the Wage-Paying", None)]},
    "Hall of the Wage-Paying": {"exits": [("Dust Shall Eat the Days", None), ("Tunnel of the Heartless", None)]},
    "Tunnel of the Heartless": {"exits": [("Hall of the Wage-Paying", None), ("The Dark Coast", None)]},
}
