room_data = {
    "Dark Abhors Light": {"exits": [("The Sunless Way", None), ("Dream of the Holy Land", None)]},
    "Dream of the Holy Land": {"exits": [("Dark Abhors Light", None), ("The Ore Road", "Aster Sigil")], "boss": "Water Elemental"},
    "The Ore Road": {"exits": [("Dream of the Holy Land", None), ("The Air Stirs", None), ("Atone for Eternity", None)], "save_point": True},
    "The Air Stirs": {"exits": [("The Ore Road", None), ("Bonds of Friendship", None), ("Bacchus is Cheap", None)]},
    "Bonds of Friendship": {"exits": [("The Air Stirs", None)], "enemy": "Air Elemental"},
    "Atone for Eternity": {"exits": [("The Ore Road", None), ("Stair to Sanctuary", None)], "traps": ["Death Vapor"]},
    "Stair to Sanctuary": {"exits": [("Atone for Eternity", None), ("The Fallen Hall", None)]},
    "The Fallen Hall": {
        "exits": [("Stair to Sanctuary", None), ("The Rotten Core", None)],
        "notes": "Spawns (Ogres/Dullahans) depend on entry door.",
    },
    "The Rotten Core": {"exits": [("The Fallen Hall", None), ("The Dreamer's Climb", None)]},
    "The Dreamer's Climb": {
        "exits": [("The Rotten Core", None), ("The Ore-Bearers", None), ("Sinner's Sustenence", "Eulelia Sigil")],
        "traps": ["Heal Panel"],
    },
    "The Ore-Bearers": {"exits": [("The Dreamer's Climb", None), ("Screams of the Wounded", None)], "traps": ["Poison Panel"]},
    "Screams of the Wounded": {
        "exits": [("The Ore-Bearers", None), ("Bacchus is Cheap", None)],
        "notes": "Spawns (Ogres/Dullahans) depend on entry door.",
    },
    "Bacchus is Cheap": {"exits": [("Screams of the Wounded", None), ("The Air Stirs", None)]},
    "Sinner's Sustenence": {"exits": [("The Dreamer's Climb", None), ("The Timely Dew of Sleep", None)]},
    "The Timely Dew of Sleep": {"exits": [("Sinner's Sustenence", None), ("The Auction Block", None), ("Companions in Arms", "Gold Key")]},
    "Companions in Arms": {"exits": [("The Timely Dew of Sleep", None)], "enemy": "Fire Elemental"},
    "The Auction Block": {
        "exits": [("The Timely Dew of Sleep", None), ("The Laborer's Bonfire", None), ("Ascension", "Silver Key")],
        "save_point": True,
    },
    "Ascension": {"exits": [("The Auction Block", None), ("Where the Serpent Hunts", None)]},
    "Where the Serpent Hunts": {"exits": [("Ascension", None), ("Drowned in Fleeting Joy", None), ("Ants Prepare for Winter", None)]},
    "Drowned in Fleeting Joy": {"exits": [("Where the Serpent Hunts", None)], "enemy": "Dark Elemental"},
    "Ants Prepare for Winter": {"exits": [("Where the Serpent Hunts", None), ("Those who Drink the Dark", None)]},
    "The Laborer's Bonfire": {
        "exits": [("The Auction Block", None), ("Stone and Sulfurous Fire", None), ("Torture Without End", "Melissa Sigil")],
        "traps": ["Paralysis Panel"],
    },
    "Stone and Sulfurous Fire": {"exits": [("The Laborer's Bonfire", None)], "enemy": "Earth Elemental"},
    "Torture Without End": {"exits": [("The Laborer's Bonfire", None), ("Way Down", None)], "boss": "Ogre Lord"},
    "Way Down": {"exits": [("Torture Without End", None), ("Excavated Hollow", None), ("Parting Regrets", None)], "save_point": True},
    "Excavated Hollow": {"exits": [("Way Down", None)], "enemy": "Water Elemental"},
    "Parting Regrets": {"exits": [("Way Down", None), ("Corridor of Tales", None)]},
    "Corridor of Tales": {"exits": [("Parting Regrets", None), ("Dust Shall Eat the Days", None)]},
    "Dust Shall Eat the Days": {"exits": [("Corridor of Tales", None), ("Hall of the Wage-Paying", None)]},
    "Hall of the Wage-Paying": {"exits": [("Dust Shall Eat the Days", None), ("Tunnel of the Heartless", None)], "boss": "Snow Dragon"},
    "Tunnel of the Heartless": {"exits": [("Hall of the Wage-Paying", None), ("The Dark Coast", None)], "is_puzzle": True},
}
