from enum import IntEnum
from typing import NamedTuple, List, Optional
import random
from BaseClasses import Item, ItemClassification


class VagrantStoryItemCategory(IntEnum):
    FILLER = 0
    RECOVERY = 1
    PERM_STAT_BOOST = 2
    TEMP_STAT_BOOST = 3
    GRIMOIRE = 4
    KEYS = 5
    SIGILS = 6
    CHAIN_ABILITY = 7
    DEFENCE_ABILITY = 8
    BREAK_ARTS = 9
    NAMED_WEAPON = 10
    BLADE_PARTS = 11
    GRIP_PARTS = 12
    SHIELDS = 13
    ARMOUR = 14
    TRAP = 15
    SKIP = 16


class VagrantStoryItemData(NamedTuple):
    name: str
    v_code: Optional[int]  # Changed to Optional[int] for flexibility with None
    category: VagrantStoryItemCategory
    progression: bool  # Added 'progression' field to the raw data


class VagrantStoryItem(Item):
    game: str = "Vagrant Story"
    category: VagrantStoryItemCategory
    v_code: Optional[int]

    def __init__(self, name: str, classification: ItemClassification, code: Optional[int], player: int):
        super().__init__(name, classification, code, player)
        # The 'advancement' attribute is automatically handled by the parent Item class
        # if ItemClassification.progression is passed to its constructor.
        # You can explicitly set it here for clarity if you prefer, but BaseClasses.Item does this.
        # self.advancement = classification == ItemClassification.progression

        # Store game-specific data directly on the item instance
        item_data = item_dictionary.get(name)
        if item_data:
            self.v_code = item_data.v_code
            self.category = item_data.category
        else:
            self.v_code = None
            self.category = VagrantStoryItemCategory.FILLER  # Fallback for unknown items

    @staticmethod
    def get_name_to_id() -> dict:
        base_id = 9901000
        # Create a dictionary mapping item names to their unique Archipelago IDs.
        return {item_data.name: (base_id + item_data.v_code) for item_data in _all_items if item_data.v_code is not None}


key_item_names = {}


_all_items: List[VagrantStoryItemData] = [
    # Recovery Items
    VagrantStoryItemData("Cure Root", 1, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Cure Bulb", 2, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Cure Tonic", 3, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Cure Potion", 4, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Mana Root", 5, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Mana Bulb", 6, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Mana Tonic", 7, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Mana Potion", 8, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Vera Root", 9, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Vera Bulb", 10, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Vera Tonic", 11, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Vera Potion", 12, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Acolyte's Nostrum", 13, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Saint's Nostrum", 14, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Alchemist's Reagent", 15, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Sorcerer's Reagent", 16, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Yggdrasil's Tears", 17, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Faerie Chortle", 18, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Spirit Orison", 19, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Angelic Paean", 20, VagrantStoryItemCategory.RECOVERY, False),
    VagrantStoryItemData("Panacea", 21, VagrantStoryItemCategory.RECOVERY, False),
    # Permanent Buffs
    VagrantStoryItemData("Elixir of Queens", 22, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Elixir of Mages", 23, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Elixir of Kings", 24, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Elixir of Sages", 25, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Elixir of Dragoon", 26, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Audentia", 27, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Virtus", 28, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Valens", 29, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Prudens", 30, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    VagrantStoryItemData("Volare", 31, VagrantStoryItemCategory.PERM_STAT_BOOST, False),
    # Temporary Stat Boosts
    VagrantStoryItemData("Snowfly Draught", 31, VagrantStoryItemCategory.TEMP_STAT_BOOST, False),  # Technically a dispel, but this works.
    VagrantStoryItemData("Faerie Wing", 32, VagrantStoryItemCategory.TEMP_STAT_BOOST, False),
    VagrantStoryItemData("Eye of Argo", 33, VagrantStoryItemCategory.TEMP_STAT_BOOST, False),
    # Grimoires
    VagrantStoryItemData("Grimoire Guerir", 34, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Mollese", 35, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Antidote", 36, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Benir", 37, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Purifier", 38, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Vie", 39, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Sylphe", 40, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Salamandre", 41, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Gnome", 42, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Undine", 43, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Parebrise", 44, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Ignifuge", 45, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Rempart", 46, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Barrer", 47, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Zephyr", 48, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Teslae", 49, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Incendie", 50, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Terre", 51, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Glace", 52, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Lux", 53, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Patire", 54, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Exsorcer", 55, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Banish", 56, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Demolir", 57, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Foudre", 58, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Flamme", 59, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Gaea", 60, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Avalanche", 61, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Radius", 62, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Meteore", 63, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Egout", 64, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Deamance", 65, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Intensite", 66, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Debile", 67, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Eclairer", 68, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Naugeux", 69, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Agilite", 70, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Tardif", 71, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Ameliore", 72, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Deteriorer", 73, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Annuler", 74, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Paralysie", 75, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Venin", 76, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Fleau", 77, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Muet", 78, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Halte", 79, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Dissiper", 80, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Clef", 81, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Visible", 82, VagrantStoryItemCategory.GRIMOIRE, False),
    VagrantStoryItemData("Grimoire Analysis", 83, VagrantStoryItemCategory.GRIMOIRE, False),
    # Keys
    VagrantStoryItemData("Bronze Key", 84, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Chest Key", 85, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Crimson Key", 86, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Gold Key", 87, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Iron Key", 88, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Platinum Key", 89, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Rood Inverse", 90, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Silver Key", 91, VagrantStoryItemCategory.KEYS, True),
    VagrantStoryItemData("Steel Key", 92, VagrantStoryItemCategory.KEYS, True),
    # Sigils
    VagrantStoryItemData("Acacia Sigil", 93, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Anemone Sigil", 94, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Aster Sigil", 95, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Azalea Sigil", 96, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Calla Sigil", 97, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Cattleya Sigil", 98, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Chamomile Sigil", 99, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Clematis Sigil", 100, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Columbine Sigil", 101, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Eulalia Sigil", 102, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Fern Sigil", 103, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Hyacith Sigil", 104, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Kalmia Sigil", 105, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Laurel Sigil", 106, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Lily Sigil", 107, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Mandrake Sigil", 108, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Marigold Sigil", 109, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Melissa Sigil", 110, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Palm Sigil", 111, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Schirra Sigil", 112, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Stock Sigil", 113, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Tearose Sigil", 114, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Tigertail Sigil", 115, VagrantStoryItemCategory.SIGILS, True),
    VagrantStoryItemData("Verbana Sigil", 116, VagrantStoryItemCategory.SIGILS, True),
    # Chain Abilities
    VagrantStoryItemData("Crimson Pain Chain Ability", 117, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Dulling Impact Chain Ability", 118, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Gain Life Chain Ability", 119, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Gain Magic Chain Ability", 120, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Heavy Shot Chain Ability", 121, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Instill Chain Ability", 122, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Mind Ache Chain Ability", 123, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Mind Assault Chain Ability", 124, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Numbing Claw Chain Ability", 125, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Paralysis Pulse Chain Ability", 126, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Phantom Pain Chain Ability", 127, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Raging Ache Chain Ability", 128, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Snake Venom Chain Ability", 129, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    VagrantStoryItemData("Temper Chain Ability", 130, VagrantStoryItemCategory.CHAIN_ABILITY, False),
    # Defence Abilities
    VagrantStoryItemData("Absorb Damage Defence Ability", 131, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Absorb Magic Defence Ability", 132, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Aqua Ward Defence Ability", 133, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Demonscale Defence Ability", 134, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Fireproof Defence Ability", 135, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Impact Guard Defence Ability", 136, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Phantom Shield Defence Ability", 137, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Reflect Damage Defence Ability", 138, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Reflect Magic Defence Ability", 139, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Shadow Guard Defence Ability", 140, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Siphon Soul Defence Ability", 141, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Terra Ward Defence Ability", 142, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Ward Defence Ability", 143, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    VagrantStoryItemData("Windbreak Defence Ability", 144, VagrantStoryItemCategory.DEFENCE_ABILITY, False),
    # Break Arts
    VagrantStoryItemData("Mistral Edge Break Art", 145, VagrantStoryItemCategory.BREAK_ARTS, False),  # Axe and Mace
    VagrantStoryItemData("Glacial Gale Break Art", 146, VagrantStoryItemCategory.BREAK_ARTS, False),  # Axe and Mace
    VagrantStoryItemData("Killer Mantis Break Art", 147, VagrantStoryItemCategory.BREAK_ARTS, False),  # Axe and Mace
    VagrantStoryItemData("Black Nebula Break Art", 148, VagrantStoryItemCategory.BREAK_ARTS, False),  # Axe and Mace
    VagrantStoryItemData("Lotus Palm Break Art", 149, VagrantStoryItemCategory.BREAK_ARTS, False),  # Bare Hands
    VagrantStoryItemData("Vertigo Break Art", 150, VagrantStoryItemCategory.BREAK_ARTS, False),  # Bare Hands
    VagrantStoryItemData("Vermillion Aura Break Art", 151, VagrantStoryItemCategory.BREAK_ARTS, False),  # Bare Hands
    VagrantStoryItemData("Retribution Break Art", 152, VagrantStoryItemCategory.BREAK_ARTS, False),  # Bare Hands
    VagrantStoryItemData("Brimstone Hail Break Art", 153, VagrantStoryItemCategory.BREAK_ARTS, False),  # Crossbow
    VagrantStoryItemData("Heaven's Scorn Break Art", 154, VagrantStoryItemCategory.BREAK_ARTS, False),  # Crossbow
    VagrantStoryItemData("Death Wail Break Art", 155, VagrantStoryItemCategory.BREAK_ARTS, False),  # Crossbow
    VagrantStoryItemData("Sanctus Flare Break Art", 156, VagrantStoryItemCategory.BREAK_ARTS, False),  # Crossbow
    VagrantStoryItemData("Whistle Sting Break Art", 157, VagrantStoryItemCategory.BREAK_ARTS, False),  # Dagger
    VagrantStoryItemData("Shadowweave Break Art", 158, VagrantStoryItemCategory.BREAK_ARTS, False),  # Dagger
    VagrantStoryItemData("Double Fang Break Art", 159, VagrantStoryItemCategory.BREAK_ARTS, False),  # Dagger
    VagrantStoryItemData("Wyrm Scorn Break Art", 160, VagrantStoryItemCategory.BREAK_ARTS, False),  # Dagger
    VagrantStoryItemData("Bear Claw Break Art", 161, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Axe
    VagrantStoryItemData("Accursed Umbra Break Art", 162, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Axe
    VagrantStoryItemData("Iron Ripper Break Art", 163, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Axe
    VagrantStoryItemData("Emetic Bomb Break Art", 164, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Axe
    VagrantStoryItemData("Sunder Break Art", 165, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Sword
    VagrantStoryItemData("Thunderwave Break Art", 166, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Sword
    VagrantStoryItemData("Swallow Slash Break Art", 167, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Sword
    VagrantStoryItemData("Advent Sign Break Art", 168, VagrantStoryItemCategory.BREAK_ARTS, False),  # Great Sword
    VagrantStoryItemData("Bonecrusher Break Art", 169, VagrantStoryItemCategory.BREAK_ARTS, False),  # Heavy Mace
    VagrantStoryItemData("Quickshock Break Art", 170, VagrantStoryItemCategory.BREAK_ARTS, False),  # Heavy Mace
    VagrantStoryItemData("Ignis Wheel Break Art", 171, VagrantStoryItemCategory.BREAK_ARTS, False),  # Heavy Mace
    VagrantStoryItemData("Hex Flux Break Art", 172, VagrantStoryItemCategory.BREAK_ARTS, False),  # Heavy Mace
    VagrantStoryItemData("Ruination Break Art", 173, VagrantStoryItemCategory.BREAK_ARTS, False),  # Polearm
    VagrantStoryItemData("Scythe Wind Break Art", 174, VagrantStoryItemCategory.BREAK_ARTS, False),  # Polearm
    VagrantStoryItemData("Giga Tempest Break Art", 175, VagrantStoryItemCategory.BREAK_ARTS, False),  # Polearm
    VagrantStoryItemData("Spiral Scourge Break Art", 176, VagrantStoryItemCategory.BREAK_ARTS, False),  # Polearm
    VagrantStoryItemData("Sirocco Break Art", 177, VagrantStoryItemCategory.BREAK_ARTS, False),  # Staff
    VagrantStoryItemData("Riskbreak Break Art", 178, VagrantStoryItemCategory.BREAK_ARTS, False),  # Staff
    VagrantStoryItemData("Gravis Aether Break Art", 179, VagrantStoryItemCategory.BREAK_ARTS, False),  # Staff
    VagrantStoryItemData("Trinity Pulse Break Art", 180, VagrantStoryItemCategory.BREAK_ARTS, False),  # Staff
    VagrantStoryItemData("Rending Gale Break Art", 181, VagrantStoryItemCategory.BREAK_ARTS, False),  # Sword
    VagrantStoryItemData("Vile Scar Break Art", 182, VagrantStoryItemCategory.BREAK_ARTS, False),  # Sword
    VagrantStoryItemData("Cherry Ronde Break Art", 183, VagrantStoryItemCategory.BREAK_ARTS, False),  # Sword
    VagrantStoryItemData("Papillon Reel Break Art", 184, VagrantStoryItemCategory.BREAK_ARTS, False),  # Sword
    # Unique Named Weapons
    VagrantStoryItemData("Fandango", 185, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Tovarisch", 187, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Seventh Heaven", 188, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Rusty Nail", 189, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Pink Squirrel", 190, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Shandy Gaff", 191, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Soul Kiss", 192, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Bosom Cleaver", 193, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Stinger", 194, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("White Cargo", 195, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Balin's Revenge", 196, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Sweet Death", 197, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Corpse Reviver", 198, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Sweet Sorrow", 199, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Eviscerator", 200, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Affinity", 201, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Dog's Nose", 202, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Pirate's Mate", 203, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Klondike", 204, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Ribsplitter", 205, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Mojito", 206, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Matador", 207, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Death Sentence", 208, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("White Lady", 209, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Angel Face", 210, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Frost Maiden", 211, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("White Rose", 212, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Bellini", 213, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Balalaika", 214, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Bull Shot", 215, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Sonora", 216, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Red Viking", 217, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Angel Lance", 218, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Magnolia Frau", 219, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Shillelagh", 220, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Czarine", 221, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Pussyfoot", 222, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Angel Kiss", 223, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Diki Diki", 224, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Blackthorn", 225, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Fallen Angel", 226, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Excalibur", 227, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Brionac", 228, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Isolde", 229, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Mjolnir", 230, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Pinaka", 231, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Sarnga", 232, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Izanagi", 233, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Dainslaif", 234, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Ascalon", 235, VagrantStoryItemCategory.NAMED_WEAPON, False),
    VagrantStoryItemData("Angel Wing", 236, VagrantStoryItemCategory.NAMED_WEAPON, False),
    # Blade Parts
    VagrantStoryItemData(
        "Battle Knife",
        257,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Daggers
    VagrantStoryItemData(
        "Scramasax",
        258,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Dirk",
        259,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Throwing Knife",
        260,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Kudi",
        261,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Cinquedea",
        262,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Kris",
        263,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Hatchet",
        264,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Khukuri",
        265,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Baselard",
        266,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Stiletto",
        267,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Jamadhar",
        268,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Spatha",
        269,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Swords
    VagrantStoryItemData(
        "Scimitar",
        270,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Rapier",
        271,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Short Sword",
        272,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Firangi",
        273,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Shamshir",
        274,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Falchion",
        275,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Shotel",
        276,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Khora",
        277,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Khopesh",
        278,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Wakizashi",
        279,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Rhomphaia",
        280,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Broad Sword",
        281,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Great Swords
    VagrantStoryItemData(
        "Norse Sword",
        282,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Katana",
        283,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Executioner",
        284,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Claymore",
        285,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Schiavona",
        286,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Bastard Sword",
        287,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Nodachi",
        288,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Rune Blade",
        289,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Holy Win",
        290,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Hand Axe",
        291,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Axes and Maces
    VagrantStoryItemData(
        "Goblin Club",
        292,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Battle Axe",
        293,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Spiked Club",
        294,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Francisca",
        295,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Ball Mace",
        296,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Tabarzin",
        297,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Footman's Mace",
        298,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Chamkaq",
        299,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Morning Star",
        300,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Tabar",
        301,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "War Hammer",
        302,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Bullova",
        303,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Bec de Corbin",
        304,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Crescent",
        305,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "War Maul",
        306,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Guisarme",
        307,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Great Axes
    VagrantStoryItemData(
        "Large Crescent",
        308,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Sabre Halberd",
        309,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Balbriggan",
        310,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Double Blade",
        311,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Halberd",
        312,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Wizard Staff",
        313,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Staves
    VagrantStoryItemData(
        "Clergy Rod",
        314,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Summoner Baton",
        315,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Shamanic Staff",
        316,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Bishop's Crosier",
        317,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Sage Cane",
        318,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Langdebeve",
        319,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Heavy Maces
    VagrantStoryItemData(
        "Sabre Mace",
        320,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Footman's Mace",
        321,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Gloomwing",
        322,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Mjolnir",
        323,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Hand of Light",
        324,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Griever",
        325,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Destroyer",
        326,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Spear",
        327,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # Polearms
    VagrantStoryItemData(
        "Glaive",
        328,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Scorpion",
        329,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Corcesca",
        330,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Trident",
        331,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Awl Pike",
        332,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Boar Spear",
        333,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Fauchard",
        334,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Voulge",
        335,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Pole Axe",
        336,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Bardysh",
        337,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Brandestoc",
        338,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Gastraph Bow",
        339,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),  # crossbows
    VagrantStoryItemData(
        "Light Crossbow",
        340,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Target Bow",
        341,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Windlass",
        342,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Cranequin",
        343,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Lug Crossbow",
        344,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Siege Bow",
        345,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    VagrantStoryItemData(
        "Arbalest",
        346,
        VagrantStoryItemCategory.BLADE_PARTS,
        False,
    ),
    # Grip Parts
    VagrantStoryItemData("Short Hilt", 347, VagrantStoryItemCategory.GRIP_PARTS, False),  # Daggers, Swords and GreatSwords
    VagrantStoryItemData("Swept Hilt", 348, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Cross Guard", 349, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Knuckle Guard", 350, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Counter Guard", 351, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Side Ring", 352, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Power Palm", 353, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Murderer's Hilt", 354, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Spiral Hilt", 355, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Wooden Grip", 356, VagrantStoryItemCategory.GRIP_PARTS, False),  # Axes, Maces and Staves
    VagrantStoryItemData("Sand Face", 357, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Grimoire Grip", 358, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Czekan Type", 359, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Sarissa Grip", 360, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Heavy Grip", 361, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Gendarme", 362, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Runkasyle", 363, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Bhuj Type", 364, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Elephant", 365, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Wooden Pole", 366, VagrantStoryItemCategory.GRIP_PARTS, False),  # Polearms
    VagrantStoryItemData("Spiculum Pole", 367, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Winged Pole", 368, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Ahlspies", 369, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Framea Pole", 370, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Spiral Pole", 371, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Simple Bolt", 372, VagrantStoryItemCategory.GRIP_PARTS, False),  # CrossBow
    VagrantStoryItemData("Steel Bolt", 373, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Stone Bullet", 374, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Javelin Bolt", 375, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Falarica Bolt", 376, VagrantStoryItemCategory.GRIP_PARTS, False),
    VagrantStoryItemData("Sonic Bullet", 377, VagrantStoryItemCategory.GRIP_PARTS, False),
    # Helmets
    VagrantStoryItemData("Leather Bandana", 378, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Bandana", 379, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Bandana", 380, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Bandana", 381, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Bandana", 382, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Bandana", 383, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Bandana", 384, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Bear Mask", 385, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Bear Mask", 386, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Bear Mask", 387, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Bear Mask", 388, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Bear Mask", 389, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Bear Mask", 390, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Bear Mask", 391, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Wizard Hat", 392, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Wizard Hat", 393, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Wizard Hat", 394, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Wizard Hat", 395, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Wizard Hat", 396, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Wizard Hat", 397, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Wizard Hat", 398, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Bone Helm", 399, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Bone Helm", 400, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Bone Helm", 401, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Bone Helm", 402, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Bone Helm", 403, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Bone Helm", 404, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Bone Helm", 405, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Chain Coif", 406, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Chain Coif", 407, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Chain Coif", 408, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Chain Coif", 409, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Chain Coif", 410, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Chain Coif", 411, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Chain Coif", 412, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Spangenhelm", 413, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Spangenhelm", 414, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Spangenhelm", 415, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Spangenhelm", 416, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Spangenhelm", 417, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Spangenhelm", 418, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Spangenhelm", 419, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Cabasset", 420, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Cabasset", 421, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Cabasset", 422, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Cabasset", 423, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Cabasset", 424, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Cabasset", 425, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Cabasset", 426, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Sallet", 427, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Sallet", 428, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Sallet", 429, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Sallet", 430, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Sallet", 431, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Sallet", 432, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Sallet", 433, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Barbut", 434, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Barbut", 435, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Barbut", 436, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Barbut", 437, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Barbut", 438, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Barbut", 439, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Barbut", 440, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Basinet", 441, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Basinet", 442, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Basinet", 443, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Basinet", 444, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Basinet", 445, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Basinet", 446, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Basinet", 447, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Armet", 448, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Armet", 449, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Armet", 450, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Armet", 451, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Armet", 452, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Armet", 453, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Armet", 454, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Close Helm", 455, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Close Helm", 456, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Close Helm", 457, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Close Helm", 458, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Close Helm", 459, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Close Helm", 460, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Close Helm", 461, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Burgonet", 462, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Burgonet", 463, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Burgonet", 464, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Burgonet", 465, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Burgonet", 466, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Burgonet", 467, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Burgonet", 468, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Hoplite Helm", 469, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Hoplite Helm", 470, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Hoplite Helm", 471, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Hoplite Helm", 472, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Hoplite Helm", 473, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Hoplite Helm", 474, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Hoplite Helm", 475, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Jazeraint Helm", 476, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jazeraint Helm", 477, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jazeraint Helm", 478, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jazeraint Helm", 479, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jazeraint Helm", 480, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jazeraint Helm", 481, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jazeraint Helm", 482, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Dread Helm", 483, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Dread Helm", 484, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Dread Helm", 485, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Dread Helm", 486, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Dread Helm", 487, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Dread Helm", 488, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Dread Helm", 489, VagrantStoryItemCategory.ARMOUR, False),
    # Chests
    VagrantStoryItemData("Leather Jerkin", 490, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jerkin", 491, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jerkin", 492, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jerkin", 493, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jerkin", 494, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jerkin", 495, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jerkin", 496, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Hauberk", 497, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Hauberk", 498, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Hauberk", 499, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Hauberk", 500, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Hauberk", 501, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Hauberk", 502, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Hauberk", 503, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Wizard Robe", 504, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Wizard Robe", 505, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Wizard Robe", 506, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Wizard Robe", 507, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Wizard Robe", 508, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Wizard Robe", 509, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Wizard Robe", 510, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Cuirass", 511, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Cuirass", 512, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Cuirass", 513, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Cuirass", 514, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Cuirass", 515, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Cuirass", 516, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Cuirass", 517, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Banded Mail", 518, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Banded Mail", 519, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Banded Mail", 520, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Banded Mail", 521, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Banded Mail", 522, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Banded Mail", 523, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Banded Mail", 524, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Ring Mail", 525, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Ring Mail", 526, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Ring Mail", 527, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Ring Mail", 528, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Ring Mail", 529, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Ring Mail", 530, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Ring Mail", 531, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Chain Mail", 532, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Chain Mail", 533, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Chain Mail", 534, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Chain Mail", 535, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Chain Mail", 536, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Chain Mail", 537, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Chain Mail", 538, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Breastplate", 539, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Breastplate", 540, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Breastplate", 541, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Breastplate", 542, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Breastplate", 543, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Breastplate", 544, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Breastplate", 545, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Segmentata", 546, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Segmentata", 547, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Segmentata", 548, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Segmentata", 549, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Segmentata", 550, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Segmentata", 551, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Segmentata", 552, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Scale Armour", 553, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Scale Armour", 554, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Scale Armour", 555, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Scale Armour", 556, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Scale Armour", 557, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Scale Armour", 558, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Scale Armour", 559, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Brigandine", 560, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Brigandine", 561, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Brigandine", 562, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Brigandine", 563, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Brigandine", 564, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Brigandine", 565, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Brigandine", 566, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Plate Mail", 567, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Plate Mail", 568, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Plate Mail", 569, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Plate Mail", 570, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Plate Mail", 571, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Plate Mail", 572, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Plate Mail", 573, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Fluted Armour", 574, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Fluted Armour", 575, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Fluted Armour", 576, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Fluted Armour", 577, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Fluted Armour", 578, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Fluted Armour", 579, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Fluted Armour", 580, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Hoplite Armour", 581, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Hoplite Armour", 582, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Hoplite Armour", 583, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Hoplite Armour", 584, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Hoplite Armour", 585, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Hoplite Armour", 586, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Hoplite Armour", 587, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Jazeraint Armour", 588, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jazeraint Armour", 589, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jazeraint Armour", 590, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jazeraint Armour", 591, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jazeraint Armour", 592, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jazeraint Armour", 593, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jazeraint Armour", 594, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Dread Armour", 595, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Dread Armour", 596, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Dread Armour", 597, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Dread Armour", 598, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Dread Armour", 599, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Dread Armour", 600, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Dread Armour", 601, VagrantStoryItemCategory.ARMOUR, False),
    # Gloves
    VagrantStoryItemData("Leather Bandage", 714, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Bandage", 715, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Bandage", 716, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Bandage", 717, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Bandage", 718, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Bandage", 719, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Bandage", 720, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Leather Glove", 721, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Leather Glove", 722, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Leather Glove", 723, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Leather Glove", 724, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Leather Glove", 725, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Leather Glove", 726, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Leather Glove", 727, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Reinforced Glove", 728, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Reinforced Glove", 729, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Reinforced Glove", 730, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Reinforced Glove", 731, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Reinforced Glove", 732, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Reinforced Glove", 733, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Reinforced Glove", 734, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Knuckles", 735, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Knuckles", 736, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Knuckles", 737, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Knuckles", 738, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Knuckles", 739, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Knuckles", 740, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Knuckles", 741, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Ring Sleeve", 742, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Ring Sleeve", 743, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Ring Sleeve", 744, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Ring Sleeve", 745, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Ring Sleeve", 746, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Ring Sleeve", 747, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Ring Sleeve", 748, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Chain Sleeve", 749, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Chain Sleeve", 750, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Chain Sleeve", 751, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Chain Sleeve", 752, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Chain Sleeve", 753, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Chain Sleeve", 754, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Chain Sleeve", 755, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Gauntlet", 756, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Gauntlet", 757, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Gauntlet", 758, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Gauntlet", 759, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Gauntlet", 760, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Gauntlet", 761, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Gauntlet", 762, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Vambrace", 763, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Vambrace", 764, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Vambrace", 765, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Vambrace", 766, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Vambrace", 767, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Vambrace", 768, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Vambrace", 769, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Plate Glove", 770, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Plate Glove", 771, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Plate Glove", 772, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Plate Glove", 773, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Plate Glove", 774, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Plate Glove", 775, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Plate Glove", 776, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Rondanche", 777, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Rondanche", 778, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Rondanche", 779, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Rondanche", 780, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Rondanche", 781, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Rondanche", 782, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Rondanche", 783, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Tilt Glove", 784, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Tilt Glove", 785, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Tilt Glove", 786, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Tilt Glove", 787, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Tilt Glove", 788, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Tilt Glove", 789, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Tilt Glove", 790, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Freiturnier", 791, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Freiturnier", 792, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Freiturnier", 793, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Freiturnier", 794, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Freiturnier", 795, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Freiturnier", 796, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Freiturnier", 797, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Fluted Glove", 798, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Fluted Glove", 799, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Fluted Glove", 800, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Fluted Glove", 801, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Fluted Glove", 802, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Fluted Glove", 803, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Fluted Glove", 804, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Hoplite Glove", 805, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Hoplite Glove", 806, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Hoplite Glove", 807, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Hoplite Glove", 808, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Hoplite Glove", 809, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Hoplite Glove", 810, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Hoplite Glove", 811, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Jazeraint Glove", 812, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jazeraint Glove", 813, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jazeraint Glove", 814, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jazeraint Glove", 815, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jazeraint Glove", 816, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jazeraint Glove", 817, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jazeraint Glove", 818, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Dread Glove", 819, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Dread Glove", 820, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Dread Glove", 821, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Dread Glove", 822, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Dread Glove", 823, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Dread Glove", 824, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Dread Glove", 825, VagrantStoryItemCategory.ARMOUR, False),
    # Leggings
    VagrantStoryItemData("Leather Sandals", 826, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Sandals", 827, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Sandals", 828, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Sandals", 829, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Sandals", 830, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Sandals", 831, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Sandals", 832, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Boots", 833, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Boots", 834, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Boots", 835, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Boots", 836, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Boots", 837, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Boots", 838, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Boots", 839, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Long Boots", 840, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Long Boots", 841, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Long Boots", 842, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Long Boots", 843, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Long Boots", 844, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Long Boots", 845, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Long Boots", 846, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Cuisse", 847, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Cuisse", 848, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Cuisse", 849, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Cuisse", 850, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Cuisse", 851, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Cuisse", 852, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Cuisse", 853, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Light Greaves", 854, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Light Greaves", 855, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Light Greaves", 856, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Light Greaves", 857, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Light Greaves", 858, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Light Greaves", 859, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Light Greaves", 860, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Ring Leggings", 861, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Ring Leggings", 862, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Ring Leggings", 863, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Ring Leggings", 864, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Ring Leggings", 865, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Ring Leggings", 866, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Ring Leggings", 867, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Chain Leggings", 868, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Chain Leggings", 869, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Chain Leggings", 870, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Chain Leggings", 871, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Chain Leggings", 872, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Chain Leggings", 873, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Chain Leggings", 874, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Fusskampf", 875, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Fusskampf", 876, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Fusskampf", 877, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Fusskampf", 878, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Fusskampf", 879, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Fusskampf", 880, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Fusskampf", 881, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Poleyn", 882, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Poleyn", 883, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Poleyn", 884, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Poleyn", 885, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Poleyn", 886, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Poleyn", 887, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Poleyn", 888, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Jambeau", 889, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jambeau", 890, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jambeau", 891, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jambeau", 892, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jambeau", 893, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jambeau", 894, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jambeau", 895, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Missaglia", 896, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Missaglia", 897, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Missaglia", 898, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Missaglia", 899, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Missaglia", 900, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Missaglia", 901, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Missaglia", 902, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Plate Leggings", 903, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Plate Leggings", 904, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Plate Leggings", 905, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Plate Leggings", 906, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Plate Leggings", 907, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Plate Leggings", 908, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Plate Leggings", 909, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Fluted Leggings", 910, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Fluted Leggings", 911, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Fluted Leggings", 912, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Fluted Leggings", 913, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Fluted Leggings", 914, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Fluted Leggings", 915, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Fluted Leggings", 916, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Hoplite Leggings", 917, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Hoplite Leggings", 918, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Hoplite Leggings", 919, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Hoplite Leggings", 920, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Hoplite Leggings", 921, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Hoplite Leggings", 922, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Hoplite Leggings", 923, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Jazeraint Leggings", 924, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Jazeraint Leggings", 925, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Jazeraint Leggings", 926, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Jazeraint Leggings", 927, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Jazeraint Leggings", 928, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Jazeraint Leggings", 929, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Jazeraint Leggings", 930, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Leather Dread Leggings", 931, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Wood Dread Leggings", 932, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Bronze Dread Leggings", 933, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Iron Dread Leggings", 934, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Hagane Dread Leggings", 935, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Silver Dread Leggings", 936, VagrantStoryItemCategory.ARMOUR, False),
    VagrantStoryItemData("Damascus Dread Leggings", 937, VagrantStoryItemCategory.ARMOUR, False),
    # Shields
    VagrantStoryItemData("Leather Buckler", 938, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Buckler", 939, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Buckler", 940, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Buckler", 941, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Buckler", 942, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Buckler", 943, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Buckler", 944, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Pelta Shield", 945, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Pelta Shield", 946, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Pelta Shield", 947, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Pelta Shield", 948, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Pelta Shield", 949, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Pelta Shield", 950, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Pelta Shield", 951, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Targe", 952, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Targe", 953, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Targe", 954, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Targe", 955, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Targe", 956, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Targe", 957, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Targe", 958, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Quad Shield", 959, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Quad Shield", 960, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Quad Shield", 961, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Quad Shield", 962, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Quad Shield", 963, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Quad Shield", 964, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Quad Shield", 965, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Circle Shield", 966, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Circle Shield", 967, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Circle Shield", 968, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Circle Shield", 969, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Circle Shield", 970, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Circle Shield", 971, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Circle Shield", 972, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Tower Shield", 973, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Tower Shield", 974, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Tower Shield", 975, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Tower Shield", 976, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Tower Shield", 977, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Tower Shield", 978, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Tower Shield", 979, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Spiked Shield", 980, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Spiked Shield", 981, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Spiked Shield", 982, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Spiked Shield", 983, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Spiked Shield", 984, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Spiked Shield", 985, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Spiked Shield", 986, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Round Shield", 987, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Round Shield", 988, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Round Shield", 989, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Round Shield", 990, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Round Shield", 991, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Round Shield", 992, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Round Shield", 993, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Kite Shield", 994, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Kite Shield", 995, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Kite Shield", 996, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Kite Shield", 997, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Kite Shield", 998, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Kite Shield", 999, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Kite Shield", 1000, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Casserole Shield", 1001, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Casserole Shield", 1002, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Casserole Shield", 1003, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Casserole Shield", 1004, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Casserole Shield", 1005, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Casserole Shield", 1006, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Casserole Shield", 1007, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Heater Shield", 1008, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Heater Shield", 1009, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Heater Shield", 1010, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Heater Shield", 1011, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Heater Shield", 1012, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Heater Shield", 1013, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Heater Shield", 1014, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Oval Shield", 1015, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Oval Shield", 1016, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Oval Shield", 1017, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Oval Shield", 1018, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Oval Shield", 1019, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Oval Shield", 1020, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Oval Shield", 1021, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Knight Shield", 1022, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Knight Shield", 1023, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Knight Shield", 1024, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Knight Shield", 1025, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Knight Shield", 1026, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Knight Shield", 1027, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Knight Shield", 1028, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Hoplite Shield", 1029, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Hoplite Shield", 1030, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Hoplite Shield", 1031, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Hoplite Shield", 1032, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Hoplite Shield", 1033, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Hoplite Shield", 1034, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Hoplite Shield", 1035, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Jazeraint Shield", 1036, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Jazeraint Shield", 1037, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Jazeraint Shield", 1038, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Jazeraint Shield", 1039, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Jazeraint Shield", 1040, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Jazeraint Shield", 1041, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Jazeraint Shield", 1042, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Leather Dread Shield", 1043, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Wood Dread Shield", 1044, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Bronze Dread Shield", 1045, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Iron Dread Shield", 1046, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Hagane Dread Shield", 1047, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Silver Dread Shield", 1048, VagrantStoryItemCategory.SHIELDS, False),
    VagrantStoryItemData("Damascus Dread Shield", 1049, VagrantStoryItemCategory.SHIELDS, False),
]
# Convert raw list of tuples into MedievilItemData NamedTuple instances
# _all_items = [VagrantStoryItemData(row[0], row[1], row[2], row[3]) for row in _all_items]


item_descriptions = {
    # Optional: Add detailed descriptions for items here
    # "Gold (50)": "A small pouch of gold coins."
}

# Create a dictionary for quick lookup of item data by name
item_dictionary: dict[str, VagrantStoryItemData] = {item_data.name: item_data for item_data in _all_items}


def BuildItemPool(count: int, options) -> List[str]:
    """
    Generates a list of item names to be used for the item pool.
    This function does NOT create Archipelago Item objects; it only provides their names.
    The actual Item objects are created in VagrantStoryWorld.create_items.

    Args:
        count (int): The total number of item names to generate.
        options: The options object from the Archipelago multiworld, used for guaranteed items.

    Returns:
        List[str]: A shuffled list of item names.
    """
    item_pool_names: List[str] = []

    # Add any guaranteed items specified in the options first
    if hasattr(options, "guaranteed_items") and options.guaranteed_items.value:
        for item_name in options.guaranteed_items.value:
            if item_name in item_dictionary:
                item_pool_names.append(item_name)
            else:
                print(f"Warning: Guaranteed item '{item_name}' not found in item_dictionary. Skipping.")

    # this needs adjusted for VS
    progression_items = [item_data.name for item_data in _all_items if item_data.progression]

    for item_name in progression_items:
        if item_name not in item_pool_names and len(item_pool_names) < count:
            item_pool_names.append(item_name)

    # Populate the rest of the pool with random filler items
    filler_item_names = [
        item_data.name
        for item_data in _all_items
        if item_data.category == VagrantStoryItemCategory.BLADE_PARTS or item_data.category == VagrantStoryItemCategory.GRIP_PARTS
    ]

    for _ in range(count - len(item_pool_names)):
        if filler_item_names:
            item_name_to_add = random.choice(filler_item_names)
            item_pool_names.append(item_name_to_add)
        else:
            print("Warning: Ran out of filler items for Vagrant Story. Duplicating from all available items.")
            # Fallback: if no specific filler items left, pick from any available item
            item_pool_names.append(random.choice(list(item_dictionary.keys())))

    random.shuffle(item_pool_names)  # Shuffle the final list of item names
    return item_pool_names
